version: 0.2

phases:
  install:
    commands:
      - echo "==== INSTALANDO DEPENDÊNCIAS ===="
      - dotnet --version
      - docker --version

  pre_build:
    commands:
      - echo "==== RESTAURANDO PACOTES ===="
      - cd invencivelAPIoficial
      - ls -la
      - dotnet restore invencivelAPIoficial.csproj  # CORRIGIDO

  build:
    commands:
      - echo "==== COMPILANDO A APLICAÇÃO ===="
      - dotnet build invencivelAPIoficial.csproj --configuration Release  # CORRIGIDO
      - cd ..
      - echo "==== CRIANDO IMAGEM DOCKER ===="
      - docker build -t invencivelapi:latest .  # Builda da raiz onde está o Dockerfile

  post_build:
    commands:
      - echo "==== BUILD FINALIZADO COM SUCESSO ===="
      - docker images
