version: "0.2"

env:
  variables:
    ImageName: invencivelapi

phases:
  install:
    commands:
      - echo "Instalando dependencias do .NET..."
      - export HOME=/root
      - export DOTNET_CLI_HOME=/root
      - wget https://dot.net/v1/dotnet-install.sh
      - bash dotnet-install.sh --channel 8.0 --install-dir /usr/share/dotnet
      - export PATH="$PATH:/usr/share/dotnet"
      - dotnet --info
      - ls -R
      - dotnet nuget locals all --clear
      - dotnet restore "invencivelAPIoficial/invencivelAPIoficial.csproj" --verbosity detailed

  pre_build:
    commands:
      - echo "Fazendo login no ECR..."
      - aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 992272338188.dkr.ecr.sa-east-1.amazonaws.com

  build:
    commands:
      - echo "Compilando aplicacao .NET..."
      - dotnet publish "invencivelAPIoficial/invencivelAPIoficial.csproj" -c Release -o ./output
      - echo "Construindo imagem Docker..."
      - docker build -t $ImageName -f ./Dockerfile ./output
      - docker images

  post_build:
    commands:
      - echo "Enviando imagem para o ECR..."
      - docker tag $ImageName:latest 992272338188.dkr.ecr.sa-east-1.amazonaws.com/$ImageName:latest
      - docker push 992272338188.dkr.ecr.sa-east-1.amazonaws.com/$ImageName:latest
