version: 0.2

phases:
  install:
    commands:
      - echo "==== INSTALANDO DEPENDÊNCIAS ===="
      - dotnet --version
      - docker --version

  pre_build:
    commands:
      - echo "==== RESTAURANDO PACOTES ===="
      - cd invencivelAPIoficial
      - dotnet restore

  build:
    commands:
      - echo "==== COMPILANDO A APLICAÇÃO ===="
      - dotnet build --configuration Release
      - echo "==== CRIANDO IMAGEM DOCKER ===="
      - docker build -t invencivelapi:latest .

  post_build:
    commands:
      - echo "==== BUILD FINALIZADO COM SUCESSO ===="
      - docker images

artifacts:
  files:
    - '**/*'
