version: 0.2

phases:
  install:
    commands:
      - echo "==== INSTALANDO DEPENDÊNCIAS ===="
      - export HOME=/root
      - export DOTNET_CLI_HOME=/tmp/dotnet
      - dotnet --version
      - docker --version

  pre_build:
    commands:
      - echo "==== RESTAURANDO PACOTES ===="
      - cd invencivelAPIoficial
      - ls -la
      - dotnet restore invencivelAPIoficial.csproj

  build:
    commands:
      - echo "==== COMPILANDO A APLICAÇÃO ===="
      - dotnet build invencivelAPIoficial.csproj --configuration Release --no-restore
      - cd ..
      - echo "==== CRIANDO IMAGEM DOCKER ===="
      - docker build -t invencivelapi:latest .

  post_build:
    commands:
      - echo "==== BUILD FINALIZADO COM SUCESSO ===="
      - docker images

artifacts:
  files:
    - '**/*'
